CREATE TABLE IF NOT EXISTS device_config_generations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_id BIGINT NOT NULL,
  generated_by_user_id BIGINT NULL,
  config_id VARCHAR(100) UNIQUE NOT NULL,
  config_version INT NOT NULL,
  config_schema_version INT DEFAULT 3,
  issued_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  wifi_ssid VARCHAR(255) NOT NULL,
  wifi_password TEXT NULL,
  address TEXT NULL,
  address_note TEXT NULL,
  mqtt_use_tls BOOLEAN DEFAULT FALSE,
  mqtt_port INT NOT NULL,
  keep_setup_ap_enabled BOOLEAN DEFAULT FALSE,
  schedule_enabled BOOLEAN DEFAULT FALSE,
  schedule_item_count INT DEFAULT 0,
  signature_hash VARCHAR(255) NULL,
  client_ip VARCHAR(100) NULL,
  user_agent TEXT NULL,
  status VARCHAR(50) DEFAULT 'generated',
  created_at DATETIME NOT NULL,
  CONSTRAINT fk_device_config_generations_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_device_config_generations_generated_by_user_id FOREIGN KEY (generated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_device_config_generations_device_version (device_id, config_version),
  INDEX idx_device_config_generations_device_id (device_id),
  INDEX idx_device_config_generations_generated_by_user_id (generated_by_user_id),
  INDEX idx_device_config_generations_status (status),
  INDEX idx_device_config_generations_created_at (created_at),
  INDEX idx_device_config_generations_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
