CREATE TABLE IF NOT EXISTS device_latest_status (
  device_id BIGINT PRIMARY KEY,
  online BOOLEAN DEFAULT FALSE,
  mode VARCHAR(50) NULL,
  is_feeding BOOLEAN DEFAULT FALSE,
  door_open BOOLEAN DEFAULT FALSE,
  wifi_connected BOOLEAN DEFAULT FALSE,
  wifi_rssi INT NULL,
  ip_address VARCHAR(100) NULL,
  server_connected BOOLEAN DEFAULT FALSE,
  time_synced BOOLEAN DEFAULT FALSE,
  epoch BIGINT NULL,
  schedule_enabled BOOLEAN DEFAULT FALSE,
  schedule_count INT DEFAULT 0,
  heap INT NULL,
  uptime_sec BIGINT NULL,
  active_config_id VARCHAR(100) NULL,
  active_config_version INT DEFAULT 0,
  last_seen_at DATETIME NULL,
  last_telemetry_at DATETIME NULL,
  updated_at DATETIME NULL,
  CONSTRAINT fk_device_latest_status_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
  INDEX idx_device_latest_status_online (online),
  INDEX idx_device_latest_status_last_seen_at (last_seen_at),
  INDEX idx_device_latest_status_last_telemetry_at (last_telemetry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS device_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_id BIGINT NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  source VARCHAR(50) NULL,
  request_id VARCHAR(100) NULL,
  config_id VARCHAR(100) NULL,
  config_version INT NULL,
  payload JSON NULL,
  device_epoch BIGINT NULL,
  created_at DATETIME NOT NULL,
  CONSTRAINT fk_device_events_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
  INDEX idx_device_events_device_id (device_id),
  INDEX idx_device_events_event_type (event_type),
  INDEX idx_device_events_request_id (request_id),
  INDEX idx_device_events_config_id (config_id),
  INDEX idx_device_events_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS device_commands (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_id BIGINT NOT NULL,
  requested_by_user_id BIGINT NULL,
  request_id VARCHAR(100) UNIQUE NOT NULL,
  action VARCHAR(100) NOT NULL,
  payload JSON NULL,
  status VARCHAR(50) DEFAULT 'pending',
  error_code VARCHAR(100) NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL,
  published_at DATETIME NULL,
  acknowledged_at DATETIME NULL,
  completed_at DATETIME NULL,
  CONSTRAINT fk_device_commands_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_device_commands_requested_by_user_id FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_device_commands_device_id (device_id),
  INDEX idx_device_commands_requested_by_user_id (requested_by_user_id),
  INDEX idx_device_commands_status (status),
  INDEX idx_device_commands_action (action),
  INDEX idx_device_commands_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS feeding_histories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_id BIGINT NOT NULL,
  source VARCHAR(50) NOT NULL,
  request_id VARCHAR(100) NULL,
  schedule_id VARCHAR(100) NULL,
  open_duration_ms INT NOT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  status VARCHAR(50) DEFAULT 'completed',
  payload JSON NULL,
  created_at DATETIME NOT NULL,
  CONSTRAINT fk_feeding_histories_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
  INDEX idx_feeding_histories_device_id (device_id),
  INDEX idx_feeding_histories_source (source),
  INDEX idx_feeding_histories_request_id (request_id),
  INDEX idx_feeding_histories_started_at (started_at),
  INDEX idx_feeding_histories_created_at (created_at),
  CONSTRAINT chk_feeding_histories_open_duration CHECK (open_duration_ms BETWEEN 100 AND 600000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
