export const ERROR_CODES = Object.freeze({
  // Generic request/auth errors
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_BODY: 'INVALID_BODY',
  INVALID_QUERY: 'INVALID_QUERY',
  INVALID_PARAMS: 'INVALID_PARAMS',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  REQUEST_ERROR: 'REQUEST_ERROR',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  HTTPS_REQUIRED: 'HTTPS_REQUIRED',
  RESERVED_OBJECT_KEY: 'RESERVED_OBJECT_KEY',

  // Auth/account errors
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_DISABLED: 'USER_DISABLED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // Device ownership/linking errors
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_ACCESS_DENIED: 'DEVICE_ACCESS_DENIED',
  DEVICE_DISABLED: 'DEVICE_DISABLED',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  INVALID_MACHINE_CODE: 'INVALID_MACHINE_CODE',
  MACHINE_CODE_NOT_FOUND: 'MACHINE_CODE_NOT_FOUND',
  INVALID_PAIRING_CODE: 'INVALID_PAIRING_CODE',
  PAIRING_CODE_ALREADY_USED: 'PAIRING_CODE_ALREADY_USED',
  DEVICE_ALREADY_LINKED: 'DEVICE_ALREADY_LINKED',
  DEVICE_ID_ALREADY_EXISTS: 'DEVICE_ID_ALREADY_EXISTS',
  MACHINE_CODE_ALREADY_EXISTS: 'MACHINE_CODE_ALREADY_EXISTS',
  INVALID_DEVICE_STATUS: 'INVALID_DEVICE_STATUS',

  // MQTT/config/schedule/command errors for later phases
  MQTT_CREDENTIAL_NOT_FOUND: 'MQTT_CREDENTIAL_NOT_FOUND',
  MQTT_SERVER_NOT_FOUND: 'MQTT_SERVER_NOT_FOUND',
  NO_ACTIVE_MQTT_SERVER: 'NO_ACTIVE_MQTT_SERVER',
  MQTT_USERNAME_ALREADY_EXISTS: 'MQTT_USERNAME_ALREADY_EXISTS',
  INVALID_WIFI_SSID: 'INVALID_WIFI_SSID',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  INVALID_SCHEDULE_TIME: 'INVALID_SCHEDULE_TIME',
  DUPLICATED_SCHEDULE_TIME: 'DUPLICATED_SCHEDULE_TIME',
  INVALID_OPEN_DURATION: 'INVALID_OPEN_DURATION',
  NEED_WIFI_SSID: 'NEED_WIFI_SSID',
  NEED_WIFI_PASSWORD: 'NEED_WIFI_PASSWORD',
  CONFIG_GENERATION_FAILED: 'CONFIG_GENERATION_FAILED',
  CONFIG_SIGNATURE_FAILED: 'CONFIG_SIGNATURE_FAILED',
  CONFIG_VERSION_CONFLICT: 'CONFIG_VERSION_CONFLICT',
  CONFIG_GENERATION_NOT_FOUND: 'CONFIG_GENERATION_NOT_FOUND',
  CONFIG_ALREADY_REVOKED: 'CONFIG_ALREADY_REVOKED',
  INVALID_CONFIG_GENERATION_STATUS: 'INVALID_CONFIG_GENERATION_STATUS',
  MQTT_DISABLED: 'MQTT_DISABLED',
  MQTT_NOT_STARTED: 'MQTT_NOT_STARTED',
  MQTT_NOT_CONNECTED: 'MQTT_NOT_CONNECTED',
  MQTT_SUBSCRIBE_FAILED: 'MQTT_SUBSCRIBE_FAILED',
  MQTT_PUBLISH_FAILED: 'MQTT_PUBLISH_FAILED',
  MQTT_CONNECTION_TEST_FAILED: 'MQTT_CONNECTION_TEST_FAILED',
  DEVICE_SECRET_ROTATION_NOT_CONFIRMED: 'DEVICE_SECRET_ROTATION_NOT_CONFIRMED',
  COMMAND_NOT_FOUND: 'COMMAND_NOT_FOUND',
  COMMAND_NOT_IN_QUEUE: 'COMMAND_NOT_IN_QUEUE',
  COMMAND_ALREADY_EXECUTED: 'COMMAND_ALREADY_EXECUTED',
  COMMAND_ACK_TIMEOUT: 'COMMAND_ACK_TIMEOUT',
  COMMAND_COMPLETE_TIMEOUT: 'COMMAND_COMPLETE_TIMEOUT',
  FEEDING_HISTORY_NOT_FOUND: 'FEEDING_HISTORY_NOT_FOUND',
  DEVICE_STALE_OFFLINE: 'DEVICE_STALE_OFFLINE'
});

export function validationCodeForSource(source) {
  if (source === 'body') return ERROR_CODES.INVALID_BODY;
  if (source === 'query') return ERROR_CODES.INVALID_QUERY;
  if (source === 'params') return ERROR_CODES.INVALID_PARAMS;
  return ERROR_CODES.VALIDATION_ERROR;
}
